name = "MechanochemicalPatterns"
uuid = "aaf28b51-dd7d-45f0-8d58-0346eb5c487c"
authors = ["Steffen Plunder <steffen.plunder@web.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
