[env]
    damping = 1.0             # pg/hr (makes mass non-dimensional)
    periodic = true
    domain = { center = [0.0, 0], size = [500.0, 500] }   # μm
    gravity = [0.0,0.0]  # μm/hr (as a velocity, assuming similar masses of all cells and stokes drag)
    dim = "julia: Val(2)"
    name = "Base"

[plot]
    alpha_soft = 0.1

[sim]
    t_end   = "julia: 48.0"  # hr
    dt      = 0.005  # hr
    saveat  = 0.1   # hr

    [sim.collision_detection]
        boxsize = 24.0  # μm
        margin = 0.1  # 0-1

[signals]
    grid = [100, 100]
    dt = 0.005  # hr
    saveat = 0.1 # hr

    [signals.types.u]
        D = 8.0   # μm²/hr
        decay = 3e-3
        init = """julia: 
                        function (x, p)
                            std = 25.0
                            return 0 * exp( -dist²(x, p.env.domain.center) / (2 * std^2) )
                        end
                        """

[mods]
    adhesion_stiffness = {speed = [0.1, -0.1], range = [0.5, 1.5], start = 12}
    new_adh_rate = {speed = [0.1, -0.1], range = [0.5, 1.5], start = 12}
    #R_hard = {speed = [0.1, 0.1], range = [5.0, 7.0], start = 12}
    #R_soft = {speed = [0.1, 0.1], range = [15.0, 17.0], start = 12}
    #R_soft = {speed = [0.1, 0.1], range = [15.0, 17.0], start = 12}
    #R_adh = {speed = [0.1, 0.1], range = [13.0, 15.0], start = 12}

[cells]
    R_soft = 15.0        # μm
    R_hard = 5.0         # μm 
    R_adh = 13.0         # μm
    R_attract = 0.0     # μm
    R_interact = 12.0    # μm (maximal interaction range)
    lifespan = "julia: NaN64" # hr
    repulsion_stiffness = 3.0 # 8.0

    attraction_stiffness = 0.0
    sigma = 0.0         # μm / √hr (for additive white noise on positions)
    sigma_p = 0.9       # μm / √hr (for active brownian particles, acts on polarity)
    plithotaxis = 0.0
    v_self_prop = 18.0      # μm/hr (speed of cells in cluster)
    
    new_adh_rate = 2.0  # 1/hr
    break_adh_rate = 3.0  # 1/hr
    adhesion_stiffness = 1.0 # 4.0  # 0.0
    
    signal_emission = 2.0
    chemotaxis_strength = 0.0 # 0.0 # 400.0

    init_pos = {uniform = "domain"}

    CIL = 0.1

    medium_active = false
    medium_repulsion = 0.0 # μm/hr
    medium_alpha = 2.0      # n.d.
    medium_slowdown = 1.0   # n.d.

    [cells.types.distal]
        ID = 1
        N = 800

        signal_emission = 0e2
        chemotaxis_strength = 0e2

        init_pos = {normal = {mean = [10.0,0.0], std = [100.0, 100.0]}}

    [cells.types.proximal]
        ID = 2
        N = 800

        signal_emission = 0.0
        chemotaxis_strength = 0e0

        init_pos = {normal = {mean = [0.0,0.0], std = [100.0, 100.0]}}

    [cells.interaction]
        adhesion_stiffness = 0.2
        new_adh_rate = 1.0  # 1/hr
        break_adh_rate = 3.0  # hr
