[env]
    damping = 1.0             # pg/hr (makes mass non-dimensional)
    periodic = true
    domain = { center = [0.0, 0], size = [1300.0, 1300.0] }   # μm
    # gravity = -0.01  # μm/hr (as a velocity, assuming similar masses of all cells and stokes drag)
    dim = "julia: Val(2)"
    name = "Sorting"

[plot]
    alpha_soft = 0.1

[sim]
    t_end   = "julia: 72.0"  # hr
    dt      = 0.005  # hr
    saveat  = 0.1   # hr

    [sim.collision_detection]
        boxsize = 18.0  # μm
        margin = 0.05  # 0-1

[signals]
    grid = [100, 100]
    dt = 0.005  # hr
    saveat = 0.1 # hr

    [signals.types.u]
        D = 8.0   # μm²/hr
        decay = 3e-3
        init = """julia: 
                        function (x, p)
                            std = 25.0
                            return 0 * exp( -dist²(x, p.env.domain.center) / (2 * std^2) )
                        end
                        """

[cells]
    R_soft = 15.0        # μm
    R_hard = 6.0         # μm 
    R_adh = 13.0         # μm
    R_attract = 0.0     # μm
    R_interact = 12.0    # μm (maximal interaction range)
    lifespan = 45  #"julia: NaN64" # hr
    repulsion_stiffness = 6.0 # 8.0

    attraction_stiffness = 0.0
    sigma = 2.0         # μm / √hr (for additive white noise on positions)
    sigma_p = 0.8       # μm / √hr (for active brownian particles, acts on polarity)
    plithotaxis = 0.0
    v_self_prop = 15.0      # μm/hr (speed of cells in cluster)
    
    #new_adh_rate = 1.0  # 1/hr
    #break_adh_rate = 3.0  # 1/hr
    #adhesion_stiffness = 1.0 # 4.0  # 0.0

    init_pos = {uniform = "domain"}

    CIL = 0.2

    medium_active = false
    medium_repulsion = 0.0 # μm/hr
    medium_alpha = 2.0      # n.d.
    medium_slowdown = 1.0   # n.d.

    [cells.types.distal]
        ID = 2
        N = 1500
    
        new_adh_rate = 1.5  # 1/hr
        break_adh_rate = 2.0  # 1/hr
        adhesion_stiffness = 0.2
        
        signal_emission = 1e2
        chemotaxis_strength = 8e1

        # init_pos = {normal = {mean = [0.0,0.0], std = [300.0, 300.0]}}

    [cells.types.proximal]
        ID = 1
        N = 1500
        
        new_adh_rate = 1.0  # 1/hr
        break_adh_rate = 3.0  # 1/hr
        adhesion_stiffness = 0.1

        signal_emission = 0.0
        chemotaxis_strength = 1e1

        # init_pos = {normal = {mean = [-20.0,0.0], std = [80.0, 80.0]}}

    [cells.interaction]
        new_adh_rate = 1.0  # 1/hr
        break_adh_rate = 3.0  # hr
        adhesion_stiffness = 0.1
