[env]
    damping = 1.0             # pg/hr (makes mass non-dimensional)
    periodic = true
    domain = { center = [0.0, 0], size = [500.0, 500.0] }   # μm
    # gravity = -0.01  # μm/hr (as a velocity, assuming similar masses of all cells and stokes drag)
    dim = "julia: Val(2)"
    name = "pure adhesion"

[plot]
    alpha_soft = 0.1

[sim]
    t_end   = "julia: 32.0"  # hr
    dt      = 0.005  # hr
    saveat  = 0.1   # hr

    [sim.collision_detection]
        boxsize = 18.0  # μm
        margin = 0.05  # 0-1

[signals]
    grid = [100, 100]
    dt = 0.005  # hr
    saveat = 0.1 # hr

    [signals.types.u]
        D = 12.0   # μm²/hr
        decay = 0.5e-2
        init = """julia: 
                        function (x, p)
                            std = 50.0
                            return 0 * exp( -dist²(p, @SVector[x[1],x[2]], @SVector([200.0,200.0])) / (2 * std^2) )
                        end
                        """

[mods]
    # adhesion_stiffness = {speed = [0.01, 0.01], range = [0.1, 0.5], start = 20}
    #new_adh_rate = {speed = [0.1, -0.1], range = [0.5, 1.5], start = 12}
    #R_hard = {speed = [0.1, 0.1], range = [5.0, 7.0], start = 12}
    #R_soft = {speed = [0.1, 0.1], range = [15.0, 17.0], start = 12}
    #R_soft = {speed = [0.1, 0.1], range = [15.0, 17.0], start = 12}
    #R_adh = {speed = [0.1, 0.1], range = [13.0, 15.0], start = 12}
    # cell_type = {random_rate = [0.005,0.002], state = [2,1], start = 6.0}
    # lifespan = {speed = [0.1, 0.1], range = [5.0, 30.0], start = 24}

[cells]
    R_soft = 15.0        # μm
    R_hard = 2.0         # μm 
    R_adh = 13.0         # μm
    R_attract = 0.0     # μm
    R_interact = 12.0    # μm (maximal interaction range)
    lifespan = "julia: NaN64" # hr
    repulsion_stiffness = 1.0 # 8.0

    attraction_stiffness = 0.0
    sigma = 0.0         # μm / √hr (for additive white noise on positions)
    sigma_p = 0.8       # μm / √hr (for active brownian particles, acts on polarity)
    plithotaxis = 0.0
    v_self_prop = 15.0      # μm/hr (speed of cells in cluster)
    
    #new_adh_rate = 1.0  # 1/hr
    #break_adh_rate = 3.0  # 1/hr
    #adhesion_stiffness = 1.0 # 4.0  # 0.0

    init_pos = {uniform = "domain"}

    CIL = 0.1

    medium_active = false
    medium_repulsion = 0.0 # μm/hr
    medium_alpha = 2.0      # n.d.
    medium_slowdown = 1.0   # n.d.

    [cells.types.distal]
        ID = 2
        N = 1000
    
        new_adh_rate = 3.0  # 1/hr
        break_adh_rate = 2.0  # 1/hr
        adhesion_stiffness = 1.2
        

        signal_emission = 3e1
        chemotaxis_strength = 1e3
        # init_pos = {normal = {mean = [0.0,0.0], std = [300.0, 300.0]}}

    [cells.types.proximal]
        ID = 1
        N = 1000
        
        new_adh_rate = 2.0  # 1/hr
        break_adh_rate = 2.0  # 1/hr
        adhesion_stiffness = 0.8

        signal_emission = 0e1
        chemotaxis_strength = 1e2

        # init_pos = {normal = {mean = [-20.0,0.0], std = [80.0, 80.0]}}

    [cells.interaction]
        new_adh_rate = 1.0  # 1/hr
        break_adh_rate = 2.0  # hr
        adhesion_stiffness = 0.3
