[env]
    damping = 1.0             # pg/hr (makes mass non-dimensional)
    periodic = true
    domain = { center = [0.0, 0], size = [500.0, 500] }   # μm
    gravity = [0.0,0.0]  # μm/hr (as a velocity, assuming similar masses of all cells and stokes drag)
    dim = "julia: Val(2)"

[sim]
    t_end   = "julia: 24.0"  # hr
    dt      = 0.005  # hr
    saveat  = 0.1   # hr

    [sim.collision_detection]
        boxsize = 24.0  # μm
        margin = 0.1  # 0-1

[signals]
    dx = 1.0   # μm
    grid = [100, 100]
    dt = 0.005  # hr
    saveat = 0.1 # hr

    [signals.types.u]
        D = 0.05   # μm²/hr
        decay = 0.0001
        init = """julia: 
                        function (x, p)
                            std = 25.0
                            return 0 * exp( -dist²(x, p.env.domain.center) / (2 * std^2) )
                        end
                        """

[cells]
    R_soft = 10.0        # μm
    R_hard = 3.0         # μm 
    R_adh = 11.0         # μm
    R_attract = 11.0     # μm
    R_interact = 11.0    # μm (maximal interaction range)
    lifespan = "julia: NaN64" # hr
    repulsion_stiffness = 10.0
    sigma = 0.0         # μm / √hr (for additive white noise)
    sigma_p = 0.1       # μm / √hr (for active brownian particles, acts on polarity)
    plithotaxis = 0.0
    v_self_prop = 5.0      # μm/hr (speed of cells in cluster)
    

    new_adh_rate = 2.5  # 1/hr
    break_adh_rate = 2.0  # 1/hr
    
    signal_emission = 3.0
    chemotaxis_strength = 1.0

    medium_active = false
    medium_repulsion = 0.0 # μm/hr
    medium_alpha = 1.0      # n.d.
    medium_slowdown = 1.0   # n.d.

    init = {R = 120.0}

    init_pos = {uniform = "domain"}

    [cells.interaction]
        attraction_stiffness = 0.0 #1
        adhesion_stiffness = 0.5
        new_adh_rate = 1.0  # 1/hr
        break_adh_rate = 2.0  # hr

    [cells.types.proximal]
        ID = 1
        N = 400


    [cells.types.distal]
        ID = 2
        N = 0
