[env]
    damping = 1.0             # pg/hr (makes mass non-dimensional)
    periodic = true
    domain = { center = [0.0, 0], size = [800.0, 800] }   # μm
    gravity = [0.0,0.0]  # μm/hr (as a velocity, assuming similar masses of all cells and stokes drag)
    dim = "julia: Val(2)"

[sim]
    t_end   = "julia: 24.0"  # hr
    dt      = 0.005  # hr
    saveat  = 0.1   # hr

    [sim.collision_detection]
        boxsize = 24.0  # μm
        margin = 0.1  # 0-1

[signals]
    grid = [100, 100]
    dt = 0.005  # hr
    saveat = 0.1 # hr

    [signals.types.u]
        D = 4.5   # μm²/hr
        decay = 0.01
        init = """julia: 
                        function (x, p)
                            std = 25.0
                            return 0 * exp( -dist²(x, p.env.domain.center) / (2 * std^2) )
                        end
                        """

[cells]
    R_soft = 10.0        # μm
    R_hard = 6.0         # μm 
    R_adh = 12.0         # μm
    R_attract = 0.0     # μm
    R_interact = 12.0    # μm (maximal interaction range)
    lifespan = "julia: NaN64" # hr
    repulsion_stiffness = 8.0
    attraction_stiffness = 0.0
    sigma = 0.0         # μm / √hr (for additive white noise)
    sigma_p = 1.0       # μm / √hr (for active brownian particles, acts on polarity)
    plithotaxis = 0.0
    v_self_prop = 15.0      # μm/hr (speed of cells in cluster)
    
    new_adh_rate = 1.0  # 1/hr
    break_adh_rate = 1.0  # 1/hr
    adhesion_stiffness = 1.0
    
    signal_emission = 2.0
    chemotaxis_strength = 100.0

    init_pos = {uniform = "domain"}


    medium_active = false
    medium_repulsion = 0.0 # μm/hr
    medium_alpha = 1.0      # n.d.
    medium_slowdown = 1.0   # n.d.

    [cells.types.proximal]
        ID = 1
        N = 1500

    [cells.types.distal]
        ID = 2
        N = 1500

        new_adh_rate = 0.0  # 1/hr

        signal_emission = 0.0
        chemotaxis_strength = 0.0

    [cells.interaction]
        adhesion_stiffness = 0.5
        new_adh_rate = 0.0  # 1/hr
        break_adh_rate = 2.0  # hr
