########################
## Configuration file ##
########################

# local folders
input_dir  = "./input"          # input files for the model
data_dir   = "./input/data"     # shared experimental datasets
output_dir = "./output"         # target for outputs (plots, videos, etc.)

# plotting options
makie_inline = true   # if true, plots are shown inside VS Code